<?php


class User extends BaseClass
{
    public $username;

    public $password;

    public $email;

    public $phone;

    public static function getTableName()
    {
        return 'users';
    }

   protected function insert()
    {
        parent::insert(); // TODO: Change the autogenerated stub
    }
}
// TDD = test driven development
